version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/bookstore?schema=public"
      JWT_SECRET: "supersecret"
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run seed && npm run start"

volumes:
  db-data:
